# Generated by Django 3.2.13 on 2022-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220418_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='blank_result',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='white_result',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
